version: "3"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/
    working_dir: /app
    command: bash -c "cd /app/public && php -S 0.0.0.0:80"
    ports:
      - "80:80"
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
